pipeline {
    agent {
        docker {
            image 'registry.cn-beijing.aliyuncs.com/mawenwu1983/maven:3.6.1-jdk-8-alpine-aliyun'
            args '-v /root/.m2:/usr/share/maven/ref/repository'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
